version: '3.8'

services:
  seq:
    image: datalust/seq:latest
    ports:
      - "5341:80"
    environment:
      - ACCEPT_EULA=Y
    
    restart: unless-stopped
    networks:
      - webnet

  # webscraper:
  #   build:
  #     context: .
  #     dockerfile: WebScraper/Dockerfile
  #   depends_on:
  #     - seq
  #   environment:
  #     - Seq__ServerUrl=http://seq:80
  #   networks:
  #     - webnet

  mongodb:
    image: mongo:7.0.8
   
    ports:
      - "27017:27017"


  




networks:
  webnet:
    driver: bridge
